data:
  train_data_path : src/resources/dataInput/train.csv
  test_data_path : src/resources/dataInput/test.csv
  final_data_path : src/resources/dataInput/processedData/final_data.csv
  missingvalue_features_90: src/resources/dataInput/processedData/missingvalue_features_90.csv
  low_variance_numerical_features: src/resources/dataInput/processedData/low_variance_numerical_features.csv
  high_correlation_features: src/resources/dataInput/processedData/high_correlation_features.csv
  single_value_features: src/resources/dataInput/processedData/single_value_features.csv
  all_dropped_features:  src/resources/dataInput/processedData/all_dropped_features.csv
  final_features: src/resources/dataInput/processedData/final_features_list.xlsv
  numerical_features_mean_median: src/resources/dataInput/processedData/numerical_features_mean_median.csv
  categorical_features_mode: src/resources/dataInput/processedData/categorical_features_mode.csv
  features_mean: src/resources/dataInput/processedData/features_mean.csv
  features_median: src/resources/dataInput/processedData/features_median.csv
  encoding_file: src/resources/dataInput/processedData/encoding_file.csv
  prompt: src/resources/dataInput/prompt.txt
  instructions: src/resources/dataInput/Instruction.txt
  column_instructions: src/resources/dataInput/column_instructions.txt
  final_prompt: src/resources/dataInput/final_prompt.txt
  validation_code: src/main/hackathon/models/validations/validations.py
  test_data_size: 0.15
  random_state: 42

model:
  pca:
    n_components: 0.9
    enable: true
  model_path: src/resources/model/anomalyDetection.pkl
  predictions_path: src/resources/dataOutput/predictions.csv
  anomalies_path: src/resources/dataOutput/anomalies.csv
  final_anomalies_path: src/resources/dataOutput/final_anomalies.csv
  scores_path_train: src/resources/dataOutput/scores_train.csv
  scores_path_test: src/resources/dataOutput/scores_test.csv
  model_name: ['DBSCAN']
  model_params:
    DBSCAN:
      eps: 8
      min_samples: 5
